"""create tables

Revision ID: 713f3bccbcce
Revises: 
Create Date: 2023-12-14 12:39:47.298233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713f3bccbcce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('dockcount', sa.Integer(), nullable=True),
    sa.Column('landmark', sa.String(), nullable=True),
    sa.Column('installation_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('status',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('bikes_available', sa.Integer(), nullable=True),
    sa.Column('docks_available', sa.Integer(), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('trips',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('start_station_name', sa.String(), nullable=True),
    sa.Column('start_station_id', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_station_name', sa.String(), nullable=True),
    sa.Column('end_station_id', sa.Integer(), nullable=True),
    sa.Column('bike_number', sa.Integer(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('subscriber_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.drop_table('usuarios')
    op.drop_table('tabela_exemplo')
    op.drop_table('items_by_id')
    op.drop_index('index_data_platform_funnels_on_account_id_and_date', table_name='data_platform_funnels')
    op.drop_table('data_platform_funnels')
    op.drop_table('my_table')
    op.drop_table('my_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='my_model_pkey')
    )
    op.create_table('my_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='my_table_pkey')
    )
    op.create_table('data_platform_funnels',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('visitors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lead_conversions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_lead_conversions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qualified_leads', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('opportunities', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sales', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('data_platform_processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_platform_funnels_pkey')
    )
    op.create_index('index_data_platform_funnels_on_account_id_and_date', 'data_platform_funnels', ['account_id', 'date'], unique=False)
    op.create_table('items_by_id',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='items_by_id_pkey')
    )
    op.create_table('tabela_exemplo',
    sa.Column('coluna1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('coluna2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('coluna3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('coluna4', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tabela_exemplo_pkey')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('social_insurance_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('key_skill', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('street_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('street_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cc_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('plan', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('term', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='usuarios_pkey')
    )
    op.drop_table('trips')
    op.drop_table('status')
    op.drop_table('stations')
    # ### end Alembic commands ###
